### ISSUE TITLE
Could not resolve hostname earth.sol.milkway

### ISSUE THREAD

**Issue by A-thaVan** [zimmertr/TKS-Bootstrap_Proxmox#7]
When I tried running this Ansible command after updating to Ansible 2.9, I got an error when it was trying to install the sudo package.  Currently my node and cluster are not referred to as earth or sol.  Is this a requirement to successfully run this command?

ansible-playbook -i inventory.yml TKS-Bootstrap_Proxmox/Ansible/create_user_account.yml

fatal: [earth.sol.milkyway]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname earth.sol.milkway: Name or service not known", "unreachable": true}

![image](https://user-images.githubusercontent.com/1687125/108707896-aed9c080-74de-11eb-8cae-31ccb0c4ec44.png)

**Comment by A-thaVan** [comment]
Problem solved.  In order to minimize changes to the inventory.yml, I mapped my server IP to the earth.sol.milkyway hostname by editing /etc/hosts (%WINDIR%\System32\drivers\etc\hosts for those like me using WSL in Windows).  

Then I had to use "ssh-keygen -t rsa" to generate the ssh keypair.  The export variable, TKS_BP_V_PROXMOX_SSH_KEY, would have to reflect whatever location and name used.

I recommend these additional steps are added to the README for completeness.

**Comment by zimmertr** [comment]
Ansible normally has its remote targets declared via an [inventory](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html) file. The reason you were seeing that FQDN was because it is the name of my personal Proxmox server. 

You can update this information [here](https://github.com/zimmertr/TKS/blob/master/inventory.yml). I've added a note to the README [here](https://github.com/zimmertr/TKS/commit/33c3a4921c44d6547c0996fe0e159007ca9a7e36) as well.
