### ISSUE TITLE
Bootable USB

### ISSUE THREAD

**Issue by A-thaVan** [zimmertr/TKS-Bootstrap_Proxmox#8]
I think it would be more accurate to rename your "Bootable USB" heading to "Bootable USB Installer".

Also, the export command uses a broken link for the Proxmox ISO.  You may want to direct people to visit the Proxmox website and copy the link to the latest ISO installer.  For example, with v6.3, the command should be:

export TKS_BM_V_PROXMOX_ISO_URL="https://proxmox.com/en/downloads?task=callelement&format=raw&item_id=551&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=b782f2e70710a9c0523a86a503b7c4e2"

Other than flashing a USB with the ISO, I thought the installation process would be preconfigured or configured for unattended installation by using the Ansible script.  I did not find that to be the case; I was still asked all the usual questions when setting up the server.  If this was intended, I recommend that you also add a line for Windows users to just download the ISO and use Etcher to flash a USB.

**Comment by zimmertr** [comment]
> I think it would be more accurate to rename your "Bootable USB" heading to "Bootable USB Installer".

I could see how this could be confusing. Updated [here](https://github.com/zimmertr/TKS-Bootstrap_Proxmox/commit/2688e99d8a5b6d0124f654352cb1469e1c635841#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R43).

> Also, the export command uses a broken link for the Proxmox ISO. You may want to direct people to visit the Proxmox website and copy the link to the latest ISO installer. For example, with v6.3, the command should be:

`export` is simply used to set configuration variables. Since every user will have a different configuration it made sense in my head that they wouldn't just copy paste my examples. In this case, though, I can see why that might be the case given how weird the URL is. I added a note about where to find the latest ISO [here](https://github.com/zimmertr/TKS-Bootstrap_Proxmox/commit/b557bd5ed44ac68e214dc2408d7a4a22d9e18f16).

>  I thought the installation process would be preconfigured..

Ya know this is a good idea, not sure why I didn't do that. While this project is branded as "Best Practices for Getting Started with K8s" or whatever, it's really just a rotating door of the latest IaC/CaC I wrote to build my homelab. So at the time I just didn't think of that.  Looks like it is [supported](https://pve.proxmox.com/wiki/Unattended_installation_of_Proxmox). The next time I rebuild my lab I'll leverage that approach. In the interim, PRs are accepted. :) 

>  for Windows users

Nah lol. 

_More seriously,_ I guess I could test with my gaming computer but I'm not really interested in developing on Windows. I usually use Arch Linux or MacOS. If you have any insight I would welcome a PR though.
